package com.agh.riceitclient.util;

public enum SportType {
    RUNNING_4,
    RUNNING_5,
    RUNNING_5_2,
    RUNNING_6,
    RUNNING_6_7,
    RUNNING_7,
    RUNNING_7_5,
    RUNNING_8,
    RUNNING_8_6,
    RUNNING_9,
    RUNNING_10,
    RUNNING_11,
    RUNNING_12,
    RUNNING_13,
    RUNNING_14,
    BICYCLING_10_TO_12,
    BICYCLING_12_TO_14,
    BICYCLING_14_TO_16,
    BICYCLING_16_TO_19,
    BICYCLING_MORE_THAN_20,
    SWIMMING_GENERAL,
    SWIMMING_BACKSTROKE,
    SWIMMING_CRAWL,
    SWIMMING_BREASTSTROKE,
    SWIMMING_BUTTERFLY;
}
